#!/usr/bin/env python
"""
PostToolUse (Bash) hook: detects git commit commands and appends an entry to
the active session log.

Known limitation: does not match env-var prefixed calls like
  `GIT_AUTHOR_NAME=x git commit -m "..."` (env-var before `git`).
These are rare in practice; silence is acceptable.
"""
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import _utils

# Matches `git commit` as an independent command token (not `git commit-msg`, etc.)
_GIT_COMMIT_RE = re.compile(r'(?:^|&&|\|\||;|\n)\s*git commit\b')


def _extract_commit_message(command: str) -> str:
    """Extract commit message from the bash command string."""
    # Double-quoted -m
    m = re.search(r'-m\s+"([^"]+)"', command)
    if m:
        return m.group(1)
    # Single-quoted -m
    m = re.search(r"-m\s+'([^']+)'", command)
    if m:
        return m.group(1)
    # Heredoc: first non-empty line after <<'EOF' or <<"EOF"
    m = re.search(r"<<['\"]?EOF['\"]?\s*\n(.*?)EOF", command, re.DOTALL)
    if m:
        for line in m.group(1).splitlines():
            stripped = line.strip()
            if stripped:
                return stripped
    return "(message not parsed)"


def _get_git_hash() -> str:
    """Return short hash of HEAD (7 chars), or '???' on failure."""
    try:
        r = subprocess.run(
            ["git", "log", "--oneline", "-1"],
            capture_output=True, text=True, timeout=3
        )
        if r.returncode == 0 and r.stdout.strip():
            return r.stdout.strip().split()[0][:7]
    except (OSError, subprocess.TimeoutExpired):
        pass
    return "???"


def main():
    # Silent in autonomous mode
    if _utils.is_autonomous_mode():
        sys.exit(0)

    # Read hook input
    try:
        hook_input = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError):
        sys.exit(0)

    command = hook_input.get("tool_input", {}).get("command", "")
    if not command or not _GIT_COMMIT_RE.search(command):
        sys.exit(0)

    # Skip autosync commits. They are generated by scripts/git-autosync.sh
    # on a periodic schedule. Logging them would append a new line to the
    # session log, re-dirtying the working tree and causing the next
    # autosync tick to commit again — a perpetual 5-minute loop even
    # during idle periods.
    if _extract_commit_message(command).startswith("autosync:"):
        sys.exit(0)

    # Get commit hash
    current_hash = _get_git_hash()

    # Dry-run guard: if hash matches last recorded hash, no new commit happened
    session_dir = _utils.get_session_dir()
    hash_file = session_dir / "commit-logger-last-hash.txt"
    last_hash = ""
    if hash_file.exists():
        try:
            last_hash = hash_file.read_text(encoding="utf-8").strip()
        except OSError:
            pass
    if current_hash == last_hash or current_hash == "???":
        sys.exit(0)

    # Record new hash
    try:
        hash_file.write_text(current_hash, encoding="utf-8")
    except OSError:
        pass

    # Find or create session log
    latest_log = _utils.find_latest_session_log()
    if latest_log is None:
        today = datetime.now().strftime("%Y-%m-%d")
        sessions_dir = Path("quality_reports/sessions")
        try:
            sessions_dir.mkdir(parents=True, exist_ok=True)
            latest_log = sessions_dir / f"{today}_auto.md"
            if not latest_log.exists():
                latest_log.write_text(
                    f"# Session Log: Auto-Created\n"
                    f"**Date:** {today}\n"
                    f"**Goal:** (auto-created by commit-logger hook)\n\n"
                    f"## Progress Log\n",
                    encoding="utf-8"
                )
        except OSError:
            sys.exit(0)

    # Append commit entry
    msg = _extract_commit_message(command)
    time_str = datetime.now().strftime("%H:%M")
    try:
        with open(latest_log, "a", encoding="utf-8") as f:
            f.write(f"- [{time_str}] Committed: {msg} ({current_hash})\n")
    except OSError:
        pass

    # No stdout output — hook passes through silently
    sys.exit(0)


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        try:
            from pathlib import Path as _P
            from datetime import datetime as _dt
            _log = _P.home() / ".claude" / "hook-errors" / "errors.log"
            _log.parent.mkdir(parents=True, exist_ok=True)
            with _log.open("a") as _fh:
                _fh.write(f"{_dt.now().isoformat()} {_P(__file__).name}: {e}\n")
        except Exception:
            pass
        sys.exit(0)
